# Generated by Django 5.1.1 on 2024-09-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buzen_Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
