# Generated by Django 5.2.6 on 2025-09-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzen_Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='jamendo_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buzen_Main.artist'),
        ),
    ]
