# Generated by Django 5.2.6 on 2025-09-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzen_Main', '0002_music_audio_url_music_jamendo_id_alter_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buzen_Main.client'),
        ),
    ]
