# Generated by Django 5.1.1 on 2024-10-03 03:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzen_Main', '0002_rename_cliente_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='favoritegender',
            name='gender_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='musichistory',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='client',
            name='born_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buzen_Main.user'),
        ),
    ]
