# Generated by Django 5.2.6 on 2025-09-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buzen_Main', '0003_alter_artist_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
