# Generated by Django 5.1.1 on 2024-10-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buzen_Main', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
